version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"
    groups:
      go:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
