run:
  timeout: 5m
  skip-dirs:
    - gen

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - gocognit # allow higher cognitive complexity
    - testpackage # unwanted convention
    - nestif # allow deep nesting
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - dogsled # allow blank identifiers
    - cyclop # allow complex functions
    - nlreturn # allow return/break without whitespace
    - exhaustive # TODO: make switches exhaustive and enable
    - noctx # TODO: update http calls and enable
    - wrapcheck # TODO: don't require error wrapping
    - paralleltest # TODO: make tests parallel and enable
    - forbidigo # TODO: remove Printf from CLI tools and enable
    - exhaustivestruct # don't require exhaustive structs
    - ifshort # has false positives in 1.37.0
