plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      releaseRules:
        # Given Go v2+ conventions we disable major releases on
        # breaking changes and leave it up to the developer
        # to make major releases
        - breaking: true
          release: "minor"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

branches: ["master"]
# github plugin is the only one running this step and we're not interested
# in its updates to PR and issues
success: false
# github plugin is the only one running this step and we're not interested
# the issues it creates due to failed releases
fail: false
