// Code generated by "stringer -type SendType -trimprefix SendType"; DO NOT EDIT.

package descriptor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SendTypeNone-0]
	_ = x[SendTypeCyclic-1]
	_ = x[SendTypeEvent-2]
}

const _SendType_name = "NoneCyclicEvent"

var _SendType_index = [...]uint8{0, 4, 10, 15}

func (i SendType) String() string {
	if i >= SendType(len(_SendType_index)-1) {
		return "SendType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SendType_name[_SendType_index[i]:_SendType_index[i+1]]
}
