// Code generated by "stringer -type TransceiverError -trimprefix TransceiverError"; DO NOT EDIT.

package socketcan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransceiverErrorUnspecified-0]
	_ = x[TransceiverErrorCANHNoWire-4]
	_ = x[TransceiverErrorCANHShortToBat-5]
	_ = x[TransceiverErrorCANHShortToVCC-6]
	_ = x[TransceiverErrorCANHShortToGND-7]
	_ = x[TransceiverErrorCANLNoWire-64]
	_ = x[TransceiverErrorCANLShortToBat-80]
	_ = x[TransceiverErrorCANLShortToVcc-96]
	_ = x[TransceiverErrorCANLShortToGND-112]
	_ = x[TransceiverErrorCANLShortToCANH-128]
}

const (
	_TransceiverError_name_0 = "Unspecified"
	_TransceiverError_name_1 = "CANHNoWireCANHShortToBatCANHShortToVCCCANHShortToGND"
	_TransceiverError_name_2 = "CANLNoWire"
	_TransceiverError_name_3 = "CANLShortToBat"
	_TransceiverError_name_4 = "CANLShortToVcc"
	_TransceiverError_name_5 = "CANLShortToGND"
	_TransceiverError_name_6 = "CANLShortToCANH"
)

var (
	_TransceiverError_index_1 = [...]uint8{0, 10, 24, 38, 52}
)

func (i TransceiverError) String() string {
	switch {
	case i == 0:
		return _TransceiverError_name_0
	case 4 <= i && i <= 7:
		i -= 4
		return _TransceiverError_name_1[_TransceiverError_index_1[i]:_TransceiverError_index_1[i+1]]
	case i == 64:
		return _TransceiverError_name_2
	case i == 80:
		return _TransceiverError_name_3
	case i == 96:
		return _TransceiverError_name_4
	case i == 112:
		return _TransceiverError_name_5
	case i == 128:
		return _TransceiverError_name_6
	default:
		return "TransceiverError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
