name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master

      - name: Make
        run: make

      - name: Create Release
        id: release
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true

      # Update tags for goreleaser to choose latest version
      - name: Fetch tags
        if: steps.release.outputs.version != ''
        run: git fetch --force --tags

      - name: Run goreleaser
        if: steps.release.outputs.version != ''
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
